/* UI15 Phase B — Qaloon Libya: ayah timing, repeat/range, tafsir and ayah metadata. */
(function(){'use strict';
 const K='zad_qaloon_reader_state', BASE='quran-libya-data/';
 const defaults={mode:'qaloon-libya',surah:1,ayah:1,page:1,reciter:'dokali',speed:1,repeat:'1',rangeStart:1,rangeEnd:1};
 const reciters=[['dokali','الدّوكالي محمد العالم','dokali_qaloon','https://server7.mp3quran.net/dokali/'],['husary','محمود خليل الحصري — قالون','husary_qaloon','https://server13.mp3quran.net/husr/Rewayat-Qalon-A-n-Nafi/'],['hudhaifi','علي الحذيفي — قالون','hudhaifi_qaloon','https://server9.mp3quran.net/huthifi_qalon/'],['ahmed_trabelsi','أحمد الطرابلسي','ahmed_trabelsi','https://server10.mp3quran.net/trablsi/'],['tariq_daoub','طارق عبدالغني دعوب','tariq_daoub','https://server10.mp3quran.net/tareq/'],['ahmed_deban','أحمد ديبان','ahmed_deban','https://server16.mp3quran.net/deban/Rewayat-Qalon-A-n-Nafi/'],['mohamed_abusneina','محمد أبو سنينة','mohamed_abusneina','https://server16.mp3quran.net/sneineh/Rewayat-Qalon-A-n-Nafi/'],['ali_alyounse','علي اليونسي','ali_alyounse','https://quran-audio.abdeljawad.com/audio/ali_alyounse/'],['taha_alfahd','طه الفهد','taha_alfahd','https://quran-audio.abdeljawad.com/audio/taha_alfahd/'],['ibrahim_kishidan','إبراهيم كشيدان','ibrahim_kishidan','https://quran-audio.abdeljawad.com/audio/ibrahim_kishidan/'],['walid_alnaehi','وليد النائحي','walid_alnaehi','https://quran-audio.abdeljawad.com/audio/walid_alnaehi/']];
 const cache=new Map(); let audio=null,timer=null,run=null;
 function state(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(K)||'{}'))}catch(_){return {...defaults}}}
 function save(p){const s=Object.assign(state(),p);localStorage.setItem(K,JSON.stringify(s));return s}
 async function load(name){if(cache.has(name))return cache.get(name);const p=fetch(BASE+name).then(r=>{if(!r.ok)throw Error(name);return r.json()});cache.set(name,p);return p}
 function rec(){return reciters.find(r=>r[0]===state().reciter)||reciters[0]}
 function pad(n){return String(n).padStart(3,'0')}
 function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 async function regionFor(s,a){const d=await load('ayah-regions.json');return d.ayahs.find(x=>x.surah===+s&&x.ayah===+a)||null}
 async function timingFor(s,a){const r=rec();const d=await load(r[2]+'-timings.json');return (d[String(s)]||[]).find(x=>x.ayah===+a)||null}
 async function syncPage(s,a){const x=await regionFor(s,a);if(x)save({surah:+s,ayah:+a,page:x.page});return x}
 function panel(surah,ayah){const s=save({surah:+surah,ayah:+ayah});return `<section class="qaloon-panel" aria-label="إعدادات مصحف قالون"><div><span class="qaloon-badge">مصحف ليبيا • رواية قالون</span><h3>الاستماع والحفظ</h3><div id="qaloon-position" class="qaloon-position">سورة ${s.surah} • آية ${s.ayah} • صفحة ${s.page}</div></div><div class="qaloon-grid"><label>القارئ<select id="qaloon-reciter">${reciters.map(r=>`<option value="${r[0]}" ${s.reciter===r[0]?'selected':''}>${r[1]}</option>`).join('')}</select></label><label>السرعة<select id="qaloon-speed">${[.75,1,1.25,1.5].map(v=>`<option value="${v}" ${Number(s.speed)===v?'selected':''}>${v}×</option>`).join('')}</select></label><label>تكرار الآية<select id="qaloon-repeat">${['1','3','5','10','continuous'].map(v=>`<option value="${v}" ${s.repeat===v?'selected':''}>${v==='continuous'?'مستمر':v+'×'}</option>`).join('')}</select></label><label>النطاق<input id="qaloon-range" value="${s.rangeStart}-${s.rangeEnd}" inputmode="numeric" aria-label="نطاق الآيات"></label></div><div class="qaloon-actions"><button type="button" id="qaloon-play"><i class="fas fa-play"></i> تشغيل الآية</button><button type="button" id="qaloon-play-surah"><i class="fas fa-circle-play"></i> تشغيل السورة كاملة</button><button type="button" id="qaloon-pause"><i class="fas fa-pause"></i> إيقاف مؤقت/متابعة</button><button type="button" id="qaloon-stop"><i class="fas fa-stop"></i> إيقاف</button><button type="button" id="qaloon-info"><i class="fas fa-circle-info"></i> معلومات الآية</button></div><div id="qaloon-status" class="qaloon-status" aria-live="polite">جاهز</div><div id="qaloon-info-sheet" class="ayah-info-sheet" hidden><div class="ayah-info-tabs"><button data-info="muyassar">التفسير الميسر</button><button data-info="saadi">السعدي</button><button data-info="asbab">أسباب النزول</button><button data-info="irab">الإعراب</button><button data-info="mutashabihat">المتشابهات</button></div><div id="qaloon-info-content" aria-live="polite">اختر قسمًا.</div></div></section>`}
 function stop(){if(timer){clearInterval(timer);timer=null} if(audio){audio.pause();audio=null} run=null;document.querySelector('#qaloon-status')?.replaceChildren(document.createTextNode('متوقف'))}
 function activate(surah,ayah){save({surah:+surah,ayah:+ayah});highlight(surah,ayah);window.dispatchEvent(new CustomEvent('zad:quran-ayah-active',{detail:{surah:+surah,ayah:+ayah}}));}
 async function playAyah(surah,ayah,opts={}){window.stopDhikrAudio?.();window.stopQuranAyahAudio?.();window.stopSurahAudio?.();stop();const t=await timingFor(surah,ayah);if(!t)throw Error('هذه النقطة مستبعدة لأن توقيتها في المصدر غير صالح');const r=rec(), st=state();audio=new Audio(r[3]+pad(surah)+'.mp3');audio.playbackRate=Number(st.speed)||1;run={surah:+surah,ayah:+ayah,done:0,target:st.repeat==='continuous'?Infinity:Number(st.repeat)||1,range:opts.range!==false};const status=document.querySelector('#qaloon-status');
  await syncPage(surah,ayah); activate(surah,ayah); audio.currentTime=t.start_ms/1000; await audio.play(); if(status)status.textContent=`تشغيل الآية ${ayah} • التكرار 1 من ${run.target===Infinity?'∞':run.target}`;
  timer=setInterval(async()=>{if(!audio||!run)return;if(audio.currentTime*1000>=t.end_ms-80){run.done++;if(run.done<run.target){audio.currentTime=t.start_ms/1000;await audio.play();if(status)status.textContent=`تشغيل الآية ${ayah} • التكرار ${run.done+1} من ${run.target===Infinity?'∞':run.target}`;return}const st2=state();if(run.range&&+ayah<+st2.rangeEnd){const next=+ayah+1;activate(surah,next);playAyah(surah,next,{range:true}).catch(showError)}else{stop();if(status)status.textContent='اكتمل التشغيل';}}},120);
 }
 async function playSurah(surah,startAyah=null){
  window.stopDhikrAudio?.();window.stopQuranAyahAudio?.();window.stopSurahAudio?.();stop();
  const r=rec(), d=await load(r[2]+'-timings.json'), list=(d[String(surah)]||[]).slice().sort((a,b)=>a.ayah-b.ayah);
  if(!list.length)throw Error('لا توجد توقيتات لهذه السورة');
  const st=save({surah:+surah,ayah:+(startAyah||list[0].ayah),rangeStart:+list[0].ayah,rangeEnd:+list[list.length-1].ayah});
  const startIndex=startAyah==null?0:Math.max(0,list.findIndex(x=>x.ayah>=+startAyah));
  const target=st.repeat==='continuous'?Infinity:Math.max(1,Number(st.repeat)||1);
  audio=new Audio(r[3]+pad(surah)+'.mp3'); audio.playbackRate=Number(st.speed)||1;
  run={type:'surah',surah:+surah,index:startIndex,list,target,cycles:1}; const status=document.querySelector('#qaloon-status');
  await syncPage(surah,list[startIndex].ayah); activate(surah,list[startIndex].ayah); audio.currentTime=list[startIndex].start_ms/1000; await audio.play();
  if(status)status.textContent=`تشغيل السورة كاملة • الآية ${list[startIndex].ayah} من ${list.length} • التكرار 1 من ${target===Infinity?'∞':target}`;
  timer=setInterval(()=>{if(!audio||!run||run.type!=='surah')return;const ms=audio.currentTime*1000;let i=run.index;
    while(i+1<list.length && ms>=list[i+1].start_ms-60)i++;
    if(i!==run.index){run.index=i;activate(surah,list[i].ayah);if(status)status.textContent=`تشغيل السورة كاملة • الآية ${list[i].ayah} من ${list.length} • التكرار ${run.cycles} من ${run.target===Infinity?'∞':run.target}`;}
    const last=list[list.length-1]; if(ms>=last.end_ms-80){
      if(run.cycles<run.target){run.cycles++;run.index=0;audio.currentTime=list[0].start_ms/1000;activate(surah,list[0].ayah);if(status)status.textContent=`تشغيل السورة كاملة • الآية ${list[0].ayah} من ${list.length} • التكرار ${run.cycles} من ${run.target===Infinity?'∞':run.target}`;return;}
      stop();if(status)status.textContent='اكتمل تشغيل السورة';
    }
  },100);
 }
 function togglePause(){const status=document.querySelector('#qaloon-status');if(!audio){if(status)status.textContent='لا يوجد تشغيل حالي';return}if(audio.paused){audio.play().catch(showError);if(status)status.textContent='متابعة التشغيل';}else{audio.pause();if(status)status.textContent='متوقف مؤقتًا';}}
 function showError(e){const x=document.querySelector('#qaloon-status');if(x)x.textContent='تعذر التشغيل: '+(e?.message||e)}
 function findText(obj,s,a){if(!obj)return null;if(typeof obj==='string')return obj;const k=s+':'+a;if(obj[k])return typeof obj[k]==='string'?obj[k]:JSON.stringify(obj[k]);if(obj[String(s)]?.[String(a)])return obj[String(s)][String(a)];if(Array.isArray(obj)){const x=obj.find(v=>v&&(v.surah===+s||v.sura===+s)&&(v.ayah===+a||v.aya===+a));return x?.text||x?.content||x?.reason||null}for(const v of Object.values(obj)){if(Array.isArray(v)){const x=v.find(z=>z&&(z.surah===+s||z.sura===+s)&&(z.ayah===+a||z.aya===+a));if(x)return x.text||x.content||x.reason||JSON.stringify(x)}}return null}
 async function info(kind,s,a){if(kind==='muyassar'||kind==='saadi'){const d=await load('tafsir-'+kind+'.json');return d[String(s)]?.[String(a)]||'لا توجد مادة لهذه الآية.'}if(kind==='irab'){const d=await load('irab.json');return d[s+':'+a]||'لا يوجد إعراب مسجل لهذه الآية.'}if(kind==='asbab'){return findText(await load('quran_asbab_al_nuzool.json'),s,a)||'لا يوجد سبب نزول مسجل لهذه الآية.'}if(kind==='mutashabihat'){return findText(await load('mutashabihat.json'),s,a)||'لا توجد متشابهات مسجلة لهذه الآية.'}return ''}
 function attach(root,surah,ayah){if(!root)return;root.querySelector('.qaloon-panel')?.remove();root.insertAdjacentHTML('afterbegin',panel(surah,ayah));const q=x=>root.querySelector(x);syncPage(surah,ayah).then(x=>{if(x&&q('#qaloon-position'))q('#qaloon-position').textContent=`سورة ${surah} • آية ${ayah} • صفحة ${x.page}`});q('#qaloon-reciter')?.addEventListener('change',e=>{const was=!!audio;const current=state().ayah;save({reciter:e.target.value});if(was){playSurah(+surah,+current).catch(showError)}});q('#qaloon-speed')?.addEventListener('change',e=>save({speed:Number(e.target.value)}));q('#qaloon-repeat')?.addEventListener('change',e=>save({repeat:e.target.value}));q('#qaloon-range')?.addEventListener('change',e=>{const m=e.target.value.match(/^(\d+)\s*-\s*(\d+)$/);if(m&&+m[1]<=+m[2])save({rangeStart:+m[1],rangeEnd:+m[2]});else e.target.value=`${state().rangeStart}-${state().rangeEnd}`});q('#qaloon-info')?.addEventListener('click',()=>{const sh=q('#qaloon-info-sheet');sh.hidden=!sh.hidden});q('#qaloon-play')?.addEventListener('click',()=>playAyah(+surah,+ayah,{range:true}).catch(showError));q('#qaloon-play-surah')?.addEventListener('click',()=>playSurah(+surah).catch(showError));q('#qaloon-pause')?.addEventListener('click',togglePause);q('#qaloon-stop')?.addEventListener('click',stop);root.querySelectorAll('[data-info]').forEach(b=>b.addEventListener('click',async()=>{const c=q('#qaloon-info-content');c.textContent='جاري التحميل…';try{c.textContent=await info(b.dataset.info,+surah,+ayah)}catch(e){c.textContent='تعذر تحميل المادة.'}}));}
 function highlight(surah,ayah){document.querySelectorAll('.ayah.qaloon-active,.qaloon-text-ayah.is-active,.libya-page-ayah.is-active').forEach(x=>x.classList.remove('qaloon-active','is-active'));const el=document.getElementById(`qaloon-text-${surah}-${ayah}`)||document.getElementById(`libya-page-${surah}-${ayah}`);if(el){el.classList.add('is-active');el.scrollIntoView({block:'center',behavior:'smooth'})}syncPage(surah,ayah).then(x=>{const pos=document.querySelector('#qaloon-position');if(x&&pos)pos.textContent=`سورة ${surah} • آية ${ayah} • صفحة ${x.page}`}).catch(()=>{});}
 window.ZadQaloon={state,save,attach,highlight,activate,reciters,playAyah,playSurah,togglePause,stop,regionFor,timingFor,info};window.addEventListener('zad:quran-ayah-active',e=>highlight(e.detail.surah,e.detail.ayah));
})();
